# Generated by Django 3.0.3 on 2020-02-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.PositiveIntegerField(default=0)),
                ('year_end', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField()),
                ('pending', models.BooleanField()),
                ('contacted', models.BooleanField()),
                ('future', models.BooleanField()),
                ('notes', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('umbrella', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.PositiveIntegerField(default=0)),
                ('tuesday', models.PositiveIntegerField(default=0)),
                ('wednesday', models.PositiveIntegerField(default=0)),
                ('thursday', models.PositiveIntegerField(default=0)),
                ('friday', models.PositiveIntegerField(default=0)),
                ('saturday', models.PositiveIntegerField(default=0)),
                ('sunday', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('in_rcsa', models.BooleanField(default=False)),
                ('authentication_level', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('committees', models.ManyToManyField(related_name='users_committees', to='basic_pd_web.Committee')),
                ('companies', models.ManyToManyField(related_name='users_companies', to='basic_pd_web.Company')),
                ('majors', models.ManyToManyField(related_name='users_majors', to='basic_pd_web.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_event', models.CharField(max_length=45)),
                ('rsvp', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(related_name='events_companies', to='basic_pd_web.Company')),
                ('industries', models.ManyToManyField(related_name='events_industries', to='basic_pd_web.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=0)),
                ('month_word', models.CharField(max_length=45)),
                ('year', models.PositiveIntegerField(default=0)),
                ('hour', models.PositiveIntegerField(default=0)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('second', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(related_name='datetimes_events', to='basic_pd_web.Event')),
                ('repeats', models.ManyToManyField(related_name='datetime_repeats', to='basic_pd_web.Repeat')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_status', to='basic_pd_web.CompanyStatus'),
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(related_name='companies_industries', to='basic_pd_web.Industry'),
        ),
        migrations.CreateModel(
            name='Authenticated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('authenticator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authenticator_authenticated', to='basic_pd_web.User')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('archive', models.SmallIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('authetication', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='article_authentication', to='basic_pd_web.Authenticated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_user', to='basic_pd_web.User')),
                ('industries', models.ManyToManyField(related_name='articles_industries', to='basic_pd_web.Industry')),
                ('tags', models.ManyToManyField(related_name='articles_tags', to='basic_pd_web.Tag')),
            ],
        ),
    ]
