# Generated by Django 3.0.3 on 2020-02-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pd_web', '001_initial_set_up_justin_edited_caroline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('authenticator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authenticator_authenticated', to='basic_pd_web.User')),
            ],
        ),
    ]
