# Generated by Django 3.0.3 on 2020-02-15 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_pd_web', '0002_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authetication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='article_authentication', to='basic_pd_web.Authenticated'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
